### PR TITLE
ZEN-4359 Added more urls allowed

### PR DESCRIPTION
**Pull request by wizehive-chrismanjoine**
added a few missing urls, updated types added feature for min max date
Screen Shot 2021-09-22 at 10 23 31 AM
s

### CODE REVIEW

**Comment by tehpsalmist** [comment]
take care of my baby ;)

**Comment by wizehive-chrismanjoine** [comment]
> take care of my baby ;)

I < 3Ben

**Review by AParks — APPROVED** [review]
👍 yay thank you for these updates!! excited to take advantage

**Comment by wizehive-chrismanjoine** [comment]
> 👍 yay thank you for these updates!! excited to take advantage

I hope to provide more updates to this now that I know what I am doing here.

**Pull request merged**
